esphome:
  name: table_fan
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: "something_cool"
  password: "something_cooler"
  manual_ip:
    static_ip: 192.168.1.1
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: wifi_signal
    name: Table Fan WiFi Signal
    update_interval: 10s
  - platform: uptime
    name: Table Fan Uptime
    
    
switch:
  - platform: restart
    name: "Table Fan Restart"
  - platform: gpio
    id: table_fan_low
    name: Table Fan Low Speed
    pin:
      number: D1
      inverted: yes
    interlock: [table_fan_high]
  - platform: gpio
    id: table_fan_high
    name: Table Fan High Speed
    pin:
      number: D2
      inverted: yes
    interlock: [table_fan_low]
    

binary_sensor:
  - platform: gpio
    pin: 
      number: D5
      mode: INPUT_PULLUP
      inverted: True
    name: "Table Fan Off Button"
    on_press:
      then:
        - switch.turn_off: table_fan_low
        - switch.turn_off: table_fan_high
  - platform: gpio
    pin: 
      number: D6
      mode: INPUT_PULLUP
      inverted: True
    name: "Table Fan Low Button"
    on_press:
      then:
        - switch.turn_on: table_fan_low
  - platform: gpio
    pin: 
      number: D7
      mode: INPUT_PULLUP
      inverted: True
    name: "Table Fan High Button"
    on_press:
      then:
        - switch.turn_on: table_fan_high
        
        
   